version: '3.8'

x-nginx_environment: &nginx_environment
  environment:
    - DOMAIN_URL


services:
  pdfmachine:
    build: ./backend
    restart: unless-stopped
    command: poetry run uvicorn main:app --host=0.0.0.0 --reload
    volumes:
      - ./backend/:/app/:cached
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - pdfmachine

    volumes:
      - local_static:/var/www/local_static/
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs

volumes:
  local_static:
  acme.sh:
  certs: