version: '3.8'

x-nginx_environment: &nginx_environment
  environment:
    - DOMAIN_URL


services:
  pdfmachine:
    build: ./backend
    restart: unless-stopped
    command: poetry run uvicorn main:app --host=0.0.0.0 --reload
    volumes:
      - ./backend/:/app/:cached
    ports:
      - 8000:8000
